version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      batch-npm-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      batch-gha-deps:
        patterns:
          - "*"
